In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error

In [14]:
X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 5, 4])
model = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(f"Slope: {model.coef_}, Intercept: {model.intercept_}, Predicted: {y_pred}")
score = mean_squared_error(y_test, y_pred)
print(f"Score: {score}")

Slope: [0.78571429], Intercept: 1.5714285714285712, Predicted: [3.14285714]
Score: 0.7346938775510206


In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss, precision_score, recall_score, f1_score
X = [[1], [2], [3], [4]]
y = [0, 0, 1, 1]
model = LogisticRegression()
model.fit(X, y)
y_pred = model.predict(X)
print("Accuracy:", accuracy_score(y, y_pred))
# TP + TN/Total
print("LogLoss:", log_loss(y, y_pred))
# -1/N sum(yi * log(pi) + (1-yi) * log(1-pi))
print("Precision:", precision_score(y, y_pred))
# TP/TP + FP
print("Recall:", recall_score(y, y_pred))
# TP/TP + FN
print("F1Score:", f1_score(y, y_pred))
# 2 * P . R / P + R

Accuracy: 1.0
LogLoss: 2.220446049250313e-16
Precision: 1.0
Recall: 1.0
F1Score: 1.0


In [23]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])
model = DecisionTreeClassifier()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  1.0


In [24]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])
model = SVC(kernel='rbf')

model.fit(X, y)

y_pred = model.predict(X)

print("Accuracy: ", accuracy_score(y, y_pred))

Accuracy:  1.0


In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])
model = RandomForestClassifier(n_estimators=100, max_depth=5, criterion='gini')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy: ", accuracy_score(y_test, y_pred))

Accuracy:  1.0


In [35]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# Sample data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])

# Train model
model = xgb.XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1, random_state=42)
model.fit(X, y)
y_pred = model.predict(X)

print("Accuracy:", accuracy_score(y, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y, y_pred))

Accuracy: 0.5
Confusion Matrix:
 [[2 0]
 [2 0]]


In [43]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# Sample data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])

# Train model
model = KNeighborsClassifier(n_neighbors=2)
model.fit(X, y)
y_pred = model.predict(X)

print("Accuracy:", accuracy_score(y, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y, y_pred))

Accuracy: 0.75
Confusion Matrix:
 [[2 0]
 [1 1]]


In [47]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# Sample data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])

# Train model
model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3)
model.fit(X, y)
y_pred = model.predict(X)

print("Accuracy:", accuracy_score(y, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y, y_pred))

Accuracy: 1.0
Confusion Matrix:
 [[2 0]
 [0 2]]


In [49]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.datasets import load_iris

# Apply LDA for feature extraction (reduce to 2 features)
lda = LinearDiscriminantAnalysis(n_components=1)
X_lda = lda.fit_transform(X, y)

print("Original feature shape:", X.shape)
print("Transformed feature shape:", X_lda.shape)

Original feature shape: (4, 2)
Transformed feature shape: (4, 1)


In [50]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

# Apply LDA for feature extraction (reduce to 2 features)
lda = PCA(n_components=1)
X_lda = lda.fit_transform(X, y)

print("Original feature shape:", X.shape)
print("Transformed feature shape:", X_lda.shape)

Original feature shape: (4, 2)
Transformed feature shape: (4, 1)


In [55]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
import numpy as np

X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 5, 4])

model = Lasso(alpha=0.1)  # Alpha controls sparsity
model.fit(X, y)
y_pred = model.predict(X)

print("MSE:", mean_squared_error(y, y_pred))
print("Coefficients:", model.coef_, "Intercept:", model.intercept_)

MSE: 0.5829999999999996
Coefficients: [0.62] Intercept: 2.2


In [57]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import numpy as np

X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 5, 4])

model = Ridge(alpha=1.0)  # Alpha is the regularization strength
model.fit(X, y)
y_pred = model.predict(X)

print("MSE:", mean_squared_error(y, y_pred))
print("Coefficients:", model.coef_, "Intercept:", model.intercept_)

MSE: 0.5920138888888891
Coefficients: [0.58333333] Intercept: 2.291666666666666


In [60]:
from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_squared_error
import numpy as np

X = np.array([[1], [2], [3], [4]])
y = np.array([2, 4, 5, 4])

model = ElasticNet(alpha=0.1, l1_ratio=0.5)  # Alpha is the regularization strength
model.fit(X, y)
y_pred = model.predict(X)

print("MSE:", mean_squared_error(y, y_pred))
print("Coefficients:", model.coef_, "Intercept:", model.intercept_)

MSE: 0.5803439349112428
Coefficients: [0.63461538] Intercept: 2.1634615384615383


In [61]:
from sklearn.linear_model import RidgeCV
from sklearn.metrics import mean_squared_error

alphas = [0.1, 1.0, 10.0, 100.0]

model = RidgeCV(alphas=alphas, store_cv_values=True)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

test_error = mean_squared_error(y_test, y_pred)

print(f"Best alpha for Ridge: {model.alpha_}")
print(f"Test Error (MSE) for Ridge: {test_error}")

Best alpha for Ridge: 1.0
Test Error (MSE) for Ridge: 0.20395421436004216


C:\Users\ajinf\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_ridge.py:2375: FutureWarning: 'store_cv_values' is deprecated in version 1.5 and will be removed in 1.7. Use 'store_cv_results' instead.
  warnings.warn(


In [66]:
from sklearn.linear_model import LassoCV

alphas = [0.1, 1.0, 10.0, 100.0]

model = LassoCV(alphas=alphas, cv=2)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

test_error = mean_squared_error(y_test, y_pred)

non_zero_coefs = sum(model.coef_ != 0)

print(f"Best alpha for Lasso: {model.alpha_}")
print(f"Test Error (MSE) for Lasso: {test_error}")
print(f"Number of non-zero coefficients: {non_zero_coefs}")

Best alpha for Lasso: 0.1
Test Error (MSE) for Lasso: 0.22224489795918376
Number of non-zero coefficients: 2


C:\Users\ajinf\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 0.000e+00, tolerance: 0.000e+00
  model = cd_fast.enet_coordinate_descent(


In [80]:
import torch
import matplotlib.pyplot as plt
from torch.utils.data import TensorDataset, DataLoader

seed = 1234
torch.manual_seed(seed)

In [95]:
train_data = torch.load(r'C:\Users\ajinf\Downloads\MNIST\MNIST\processed\training.pt', weights_only=True)
test_data = torch.load(r'C:\Users\ajinf\Downloads\MNIST\MNIST\processed\test.pt', weights_only=True)

train_images, train_labels = train_data
test_images, test_labels = test_data
train_images = train_images.float().unsqueeze(1) / 255.0 
test_images = test_images.float().unsqueeze(1) / 255.0 

train_dataset = TensorDataset(train_images, train_labels)
test_dataset = TensorDataset(test_images, test_labels)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [96]:
from torch import nn
import torch

In [103]:
class CNN_Small(torch.nn.Module):
    def __init__(self):
        super(CNN_Small, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=10, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(in_channels=10, out_channels=20, kernel_size=3, stride=1, padding=1)
        self.relu = nn.ReLU()
        self.batchnn = nn.BatchNorm2d(num_features=20)
        self.fc1 = nn.Linear(320, 10)
        self.pooling = nn.MaxPool2d(kernel_size=2, padding=0, stride=2)

    def forward(self, x):
        x = self.conv2(self.conv1(x))
        x = self.relu(x)
        x = self.pooling(x)
        x = self.batchnn(x)
        x = x.view(x.size(0), -1)
        x = self.fc1(x)

        return x

In [104]:
model = CNN_Small()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

In [105]:
epoch = 1
for i in range(epoch):
    model.train()
    for img, label in train_loader:
        optimizer.zero_grad()
        outputs = model(img)
        loss = criterion(outputs, label)
        loss.backward()
        optimizer.step()

    model.eval()
    for img, label in test_loader:
        optimizer.zero_grad()
        outputs = model(img)
        loss = criterion(outputs, label)
        loss.backward()
        optimizer.step()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x3920 and 320x10)